#!/usr/bin/env bash
# =============================================================================
# PR Pilot — post-comment.sh
# Posts the review Markdown as a GitHub PR comment.
#
# Usage:
#   ./scripts/post-comment.sh <pr_number> <review_file_path>
#
# Required environment variables:
#   GITHUB_TOKEN   — GitHub personal access token with repo scope
#   GITHUB_REPO    — owner/repo format (e.g., acme/library-app)
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Argument validation
# ---------------------------------------------------------------------------
if [ "$#" -lt 2 ]; then
  echo "ERROR: Usage: $0 <pr_number> <review_file_path>" >&2
  exit 1
fi

PR_NUMBER="$1"
REVIEW_FILE="$2"

if [ ! -f "${REVIEW_FILE}" ]; then
  echo "ERROR: Review file not found: ${REVIEW_FILE}" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Environment validation
# ---------------------------------------------------------------------------
: "${GITHUB_TOKEN:?ERROR: GITHUB_TOKEN environment variable is required}"
: "${GITHUB_REPO:?ERROR: GITHUB_REPO environment variable is required}"

# ---------------------------------------------------------------------------
# Step 1: Delete any previous PR Pilot comment (avoid spam on re-runs)
# ---------------------------------------------------------------------------
COMMENTS_URL="https://api.github.com/repos/${GITHUB_REPO}/issues/${PR_NUMBER}/comments"

echo "[post-comment] Looking for existing PR Pilot comments to replace..."

EXISTING_COMMENT_IDS=$(curl --silent --fail \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "${COMMENTS_URL}?per_page=100" \
  | python3 -c "
import sys, json
comments = json.load(sys.stdin)
for c in comments:
    if c.get('user', {}).get('login', '').lower() in ('github-actions[bot]', 'pr-pilot-bot') \
       or '## PR Pilot Review' in c.get('body', ''):
        print(c['id'])
" 2>/dev/null || true)

for COMMENT_ID in ${EXISTING_COMMENT_IDS}; do
  echo "[post-comment] Deleting old PR Pilot comment ID: ${COMMENT_ID}"
  curl --silent --fail \
    -X DELETE \
    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/repos/${GITHUB_REPO}/issues/comments/${COMMENT_ID}" \
    || echo "[post-comment] WARNING: Could not delete comment ${COMMENT_ID}"
done

# ---------------------------------------------------------------------------
# Step 2: Read and wrap the review content
# ---------------------------------------------------------------------------
REVIEW_CONTENT=$(cat "${REVIEW_FILE}")

# Add a footer with metadata
FOOTER="
---
<sub>🤖 Generated by **PR Pilot** powered by IBM Bob 2.0 · [View workflow run](https://github.com/${GITHUB_REPO}/actions) · Reply **\`yes, apply fixes\`** to auto-commit low-risk suggestions</sub>"

FULL_BODY="${REVIEW_CONTENT}${FOOTER}"

# ---------------------------------------------------------------------------
# Step 3: Post the comment using the GitHub API
# ---------------------------------------------------------------------------
echo "[post-comment] Posting review comment to PR #${PR_NUMBER}..."

# Safely encode the JSON body using Python
RESPONSE=$(python3 -c "
import json, sys, urllib.request, urllib.error

body = sys.stdin.read()
payload = json.dumps({'body': body}).encode('utf-8')

req = urllib.request.Request(
    'https://api.github.com/repos/${GITHUB_REPO}/issues/${PR_NUMBER}/comments',
    data=payload,
    headers={
        'Authorization': 'Bearer ${GITHUB_TOKEN}',
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json'
    },
    method='POST'
)

try:
    with urllib.request.urlopen(req) as resp:
        data = json.loads(resp.read())
        print(data.get('html_url', 'Comment posted (no URL returned)'))
except urllib.error.HTTPError as e:
    print(f'HTTP Error {e.code}: {e.read().decode()}', file=sys.stderr)
    sys.exit(1)
" <<< "${FULL_BODY}")

echo "[post-comment] Comment posted: ${RESPONSE}"
